//! Instance methods of the rune standard library (rune 0.14.2), grouped by
//! the module that registers them — mirror of `rune::modules::*`, so a host
//! that installs only some modules can assemble the matching subset.
//!
//! GENERATED from the installed `Context::with_default_modules()` via the
//! `rune doc` CLI — do not edit by hand; regenerate after a rune upgrade
//! (see the ytaq project notes for the dump tooling).
//!
//! [`iter()`] carries the `Iterator`/`DoubleEndedIterator`/
//! `ExactSizeIterator` trait methods for all iterator-like types (whichever
//! module defines them) — without `std::iter` installed they do not exist
//! at runtime either.

use crate::types::{EnumVariant, MethodSignature, PrimitiveType, TypeDef};

fn ret(name: &str) -> Option<TypeDef> {
	match name {
		"" | "any" => None,
		"String" => Some(TypeDef::Primitive(PrimitiveType::String)),
		"bool" => Some(TypeDef::Primitive(PrimitiveType::Bool)),
		"i64" | "u64" => Some(TypeDef::Primitive(PrimitiveType::Int)),
		"f64" => Some(TypeDef::Primitive(PrimitiveType::Float)),
		"Bytes" => Some(TypeDef::Primitive(PrimitiveType::Bytes)),
		"Vec" => Some(TypeDef::List(Box::new(TypeDef::Unit))),
		"Object" => Some(TypeDef::Object(Vec::new())),
		other => Some(TypeDef::Enum(vec![EnumVariant {
			path: vec![other.to_string()],
			inner: None,
		}])),
	}
}

fn table(rows: &[(&str, &str, &str)]) -> Vec<MethodSignature> {
	rows.iter()
		.map(|(receiver, name, return_name)| MethodSignature::new(receiver, name, ret(return_name)))
		.collect()
}

/// `rune::modules::string`
pub fn string() -> Vec<MethodSignature> {
	table(&[
		("String", "as_bytes", "Bytes"),
		("String", "capacity", "u64"),
		("String", "char_at", "Option"),
		("String", "chars", "Chars"),
		("String", "clear", ""),
		("String", "contains", "bool"),
		("String", "ends_with", "bool"),
		("String", "get", "Option"),
		("String", "into_bytes", "Bytes"),
		("String", "is_empty", "bool"),
		("String", "len", "u64"),
		("String", "parse", "Result"),
		("String", "push", ""),
		("String", "push_str", ""),
		("String", "replace", "String"),
		("String", "reserve", ""),
		("String", "reserve_exact", ""),
		("String", "shrink_to_fit", ""),
		("String", "split_once", "Option"),
		("String", "starts_with", "bool"),
		("String", "to_lowercase", "String"),
		("String", "to_uppercase", "String"),
		("String", "trim", "String"),
		("String", "trim_end", "String"),
	])
}

/// `rune::modules::bytes`
pub fn bytes() -> Vec<MethodSignature> {
	table(&[
		("Bytes", "as_vec", "Vec"),
		("Bytes", "capacity", "u64"),
		("Bytes", "clear", ""),
		("Bytes", "extend", ""),
		("Bytes", "extend_str", ""),
		("Bytes", "first", "Option"),
		("Bytes", "insert", ""),
		("Bytes", "into_vec", "Vec"),
		("Bytes", "is_empty", "bool"),
		("Bytes", "last", "Option"),
		("Bytes", "len", "u64"),
		("Bytes", "pop", "Option"),
		("Bytes", "push", ""),
		("Bytes", "remove", "u64"),
		("Bytes", "reserve", ""),
		("Bytes", "reserve_exact", ""),
		("Bytes", "shrink_to_fit", ""),
	])
}

/// `rune::modules::vec`
pub fn vec() -> Vec<MethodSignature> {
	table(&[
		("Vec", "capacity", "u64"),
		("Vec", "clear", ""),
		("Vec", "extend", ""),
		("Vec", "get", "Option"),
		("Vec", "insert", ""),
		("Vec", "is_empty", "bool"),
		("Vec", "iter", "Iter"),
		("Vec", "len", "u64"),
		("Vec", "pop", "Option"),
		("Vec", "push", ""),
		("Vec", "remove", "any"),
		("Vec", "resize", ""),
		("Vec", "sort", ""),
		("Vec", "sort_by", ""),
	])
}

/// `rune::modules::object`
pub fn object() -> Vec<MethodSignature> {
	table(&[
		("Object", "clear", ""),
		("Object", "contains_key", "bool"),
		("Object", "get", "Option"),
		("Object", "insert", "Option"),
		("Object", "is_empty", "bool"),
		("Object", "iter", "Iter"),
		("Object", "keys", "Keys"),
		("Object", "len", "u64"),
		("Object", "remove", "Option"),
		("Object", "values", "Values"),
	])
}

/// `rune::modules::tuple`
pub fn tuple() -> Vec<MethodSignature> {
	table(&[
		("Tuple", "get", "Option"),
		("Tuple", "is_empty", "bool"),
		("Tuple", "iter", "Iter"),
		("Tuple", "len", "u64"),
	])
}

/// `rune::modules::hash_map`
pub fn hash_map() -> Vec<MethodSignature> {
	table(&[
		("HashMap", "capacity", "u64"),
		("HashMap", "clear", ""),
		("HashMap", "contains_key", "bool"),
		("HashMap", "extend", ""),
		("HashMap", "get", "Option"),
		("HashMap", "insert", "Option"),
		("HashMap", "is_empty", "bool"),
		("HashMap", "iter", "Iter"),
		("HashMap", "keys", "Keys"),
		("HashMap", "len", "u64"),
		("HashMap", "remove", "Option"),
		("HashMap", "values", "Values"),
	])
}

/// `rune::modules::hash_set`
pub fn hash_set() -> Vec<MethodSignature> {
	table(&[
		("HashSet", "capacity", "u64"),
		("HashSet", "clear", ""),
		("HashSet", "contains", "bool"),
		("HashSet", "difference", "Difference"),
		("HashSet", "extend", ""),
		("HashSet", "insert", "bool"),
		("HashSet", "intersection", "Intersection"),
		("HashSet", "is_empty", "bool"),
		("HashSet", "iter", "Iter"),
		("HashSet", "len", "u64"),
		("HashSet", "remove", "bool"),
		("HashSet", "union", "Union"),
	])
}

/// `rune::modules::vec_deque`
pub fn vec_deque() -> Vec<MethodSignature> {
	table(&[
		("VecDeque", "back", "Option"),
		("VecDeque", "capacity", "u64"),
		("VecDeque", "extend", ""),
		("VecDeque", "front", "Option"),
		("VecDeque", "insert", ""),
		("VecDeque", "iter", "Iter"),
		("VecDeque", "len", "u64"),
		("VecDeque", "pop_back", "Option"),
		("VecDeque", "pop_front", "Option"),
		("VecDeque", "push_back", ""),
		("VecDeque", "push_front", ""),
		("VecDeque", "remove", "Option"),
		("VecDeque", "reserve", ""),
		("VecDeque", "rotate_left", ""),
		("VecDeque", "rotate_right", ""),
	])
}

/// `rune::modules::char`
pub fn char() -> Vec<MethodSignature> {
	table(&[
		("char", "is_alphabetic", "bool"),
		("char", "is_alphanumeric", "bool"),
		("char", "is_control", "bool"),
		("char", "is_lowercase", "bool"),
		("char", "is_numeric", "bool"),
		("char", "is_uppercase", "bool"),
		("char", "is_whitespace", "bool"),
		("char", "to_digit", "Option"),
		("char", "to_i64", "i64"),
	])
}

/// `rune::modules::i64`
pub fn i64() -> Vec<MethodSignature> {
	table(&[
		("i64", "abs", "i64"),
		("i64", "checked_add", "Option"),
		("i64", "checked_div", "Option"),
		("i64", "checked_mul", "Option"),
		("i64", "checked_rem", "Option"),
		("i64", "checked_sub", "Option"),
		("i64", "is_negative", "bool"),
		("i64", "is_positive", "bool"),
		("i64", "pow", "i64"),
		("i64", "saturating_abs", "i64"),
		("i64", "saturating_add", "i64"),
		("i64", "saturating_mul", "i64"),
		("i64", "saturating_pow", "i64"),
		("i64", "saturating_sub", "i64"),
		("i64", "signum", "i64"),
		("i64", "to", "f64"),
		("i64", "to_string", "String"),
		("i64", "wrapping_add", "i64"),
		("i64", "wrapping_div", "i64"),
		("i64", "wrapping_mul", "i64"),
		("i64", "wrapping_rem", "i64"),
		("i64", "wrapping_sub", "i64"),
	])
}

/// `rune::modules::u64`
pub fn u64() -> Vec<MethodSignature> {
	table(&[
		("u64", "checked_add", "Option"),
		("u64", "checked_div", "Option"),
		("u64", "checked_mul", "Option"),
		("u64", "checked_rem", "Option"),
		("u64", "checked_sub", "Option"),
		("u64", "pow", "u64"),
		("u64", "saturating_add", "u64"),
		("u64", "saturating_mul", "u64"),
		("u64", "saturating_pow", "u64"),
		("u64", "saturating_sub", "u64"),
		("u64", "to", "f64"),
		("u64", "to_string", "String"),
		("u64", "wrapping_add", "u64"),
		("u64", "wrapping_div", "u64"),
		("u64", "wrapping_mul", "u64"),
		("u64", "wrapping_rem", "u64"),
		("u64", "wrapping_sub", "u64"),
	])
}

/// `rune::modules::f64`
pub fn f64() -> Vec<MethodSignature> {
	table(&[
		("f64", "abs", "f64"),
		("f64", "ceil", "f64"),
		("f64", "floor", "f64"),
		("f64", "is_finite", "bool"),
		("f64", "is_infinite", "bool"),
		("f64", "is_nan", "bool"),
		("f64", "is_normal", "bool"),
		("f64", "is_subnormal", "bool"),
		("f64", "powf", "f64"),
		("f64", "powi", "f64"),
		("f64", "round", "f64"),
		("f64", "sqrt", "f64"),
		("f64", "to", "i64"),
	])
}

/// `rune::modules::option`
pub fn option() -> Vec<MethodSignature> {
	table(&[
		("Option", "and_then", "Option"),
		("Option", "expect", "any"),
		("Option", "is_none", "bool"),
		("Option", "is_some", "bool"),
		("Option", "iter", "Iter"),
		("Option", "map", "Option"),
		("Option", "ok_or", "Result"),
		("Option", "ok_or_else", "Result"),
		("Option", "take", "Option"),
		("Option", "transpose", "any"),
		("Option", "unwrap", "any"),
		("Option", "unwrap_or", "any"),
		("Option", "unwrap_or_else", "any"),
	])
}

/// `rune::modules::result`
pub fn result() -> Vec<MethodSignature> {
	table(&[
		("Result", "and_then", "Result"),
		("Result", "expect", "any"),
		("Result", "is_err", "bool"),
		("Result", "is_ok", "bool"),
		("Result", "map", "Result"),
		("Result", "ok", "Option"),
		("Result", "unwrap", "any"),
		("Result", "unwrap_or", "any"),
		("Result", "unwrap_or_else", "any"),
	])
}

/// `rune::modules::iter`
pub fn iter() -> Vec<MethodSignature> {
	table(&[
		("Chain", "all", "bool"),
		("Chain", "any", "bool"),
		("Chain", "chain", "Chain"),
		("Chain", "collect", "Vec"),
		("Chain", "count", "u64"),
		("Chain", "enumerate", "Enumerate"),
		("Chain", "filter", "Filter"),
		("Chain", "filter_map", "FilterMap"),
		("Chain", "find", "Option"),
		("Chain", "flat_map", "FlatMap"),
		("Chain", "fold", "any"),
		("Chain", "len", "u64"),
		("Chain", "map", "Map"),
		("Chain", "next", "Option"),
		("Chain", "next_back", "Option"),
		("Chain", "nth", "Option"),
		("Chain", "nth_back", "Option"),
		("Chain", "peekable", "Peekable"),
		("Chain", "product", "u64"),
		("Chain", "reduce", "Option"),
		("Chain", "rev", "Rev"),
		("Chain", "size_hint", ""),
		("Chain", "skip", "Skip"),
		("Chain", "sum", "u64"),
		("Chain", "take", "Take"),
		("Chars", "all", "bool"),
		("Chars", "any", "bool"),
		("Chars", "chain", "Chain"),
		("Chars", "collect", "Vec"),
		("Chars", "count", "u64"),
		("Chars", "enumerate", "Enumerate"),
		("Chars", "filter", "Filter"),
		("Chars", "filter_map", "FilterMap"),
		("Chars", "find", "Option"),
		("Chars", "flat_map", "FlatMap"),
		("Chars", "fold", "any"),
		("Chars", "len", "u64"),
		("Chars", "map", "Map"),
		("Chars", "next", "Option"),
		("Chars", "next_back", "Option"),
		("Chars", "nth", "Option"),
		("Chars", "nth_back", "Option"),
		("Chars", "peekable", "Peekable"),
		("Chars", "product", "u64"),
		("Chars", "reduce", "Option"),
		("Chars", "rev", "Rev"),
		("Chars", "size_hint", ""),
		("Chars", "skip", "Skip"),
		("Chars", "sum", "u64"),
		("Chars", "take", "Take"),
		("Difference", "all", "bool"),
		("Difference", "any", "bool"),
		("Difference", "chain", "Chain"),
		("Difference", "collect", "Vec"),
		("Difference", "count", "u64"),
		("Difference", "enumerate", "Enumerate"),
		("Difference", "filter", "Filter"),
		("Difference", "filter_map", "FilterMap"),
		("Difference", "find", "Option"),
		("Difference", "flat_map", "FlatMap"),
		("Difference", "fold", "any"),
		("Difference", "len", "u64"),
		("Difference", "map", "Map"),
		("Difference", "next", "Option"),
		("Difference", "next_back", "Option"),
		("Difference", "nth", "Option"),
		("Difference", "nth_back", "Option"),
		("Difference", "peekable", "Peekable"),
		("Difference", "product", "u64"),
		("Difference", "reduce", "Option"),
		("Difference", "rev", "Rev"),
		("Difference", "size_hint", ""),
		("Difference", "skip", "Skip"),
		("Difference", "sum", "u64"),
		("Difference", "take", "Take"),
		("Empty", "all", "bool"),
		("Empty", "any", "bool"),
		("Empty", "chain", "Chain"),
		("Empty", "collect", "Vec"),
		("Empty", "count", "u64"),
		("Empty", "enumerate", "Enumerate"),
		("Empty", "filter", "Filter"),
		("Empty", "filter_map", "FilterMap"),
		("Empty", "find", "Option"),
		("Empty", "flat_map", "FlatMap"),
		("Empty", "fold", "any"),
		("Empty", "len", "u64"),
		("Empty", "map", "Map"),
		("Empty", "next", "Option"),
		("Empty", "next_back", "Option"),
		("Empty", "nth", "Option"),
		("Empty", "nth_back", "Option"),
		("Empty", "peekable", "Peekable"),
		("Empty", "product", "u64"),
		("Empty", "reduce", "Option"),
		("Empty", "rev", "Rev"),
		("Empty", "size_hint", ""),
		("Empty", "skip", "Skip"),
		("Empty", "sum", "u64"),
		("Empty", "take", "Take"),
		("Enumerate", "all", "bool"),
		("Enumerate", "any", "bool"),
		("Enumerate", "chain", "Chain"),
		("Enumerate", "collect", "Vec"),
		("Enumerate", "count", "u64"),
		("Enumerate", "enumerate", "Enumerate"),
		("Enumerate", "filter", "Filter"),
		("Enumerate", "filter_map", "FilterMap"),
		("Enumerate", "find", "Option"),
		("Enumerate", "flat_map", "FlatMap"),
		("Enumerate", "fold", "any"),
		("Enumerate", "len", "u64"),
		("Enumerate", "map", "Map"),
		("Enumerate", "next", "Option"),
		("Enumerate", "next_back", "Option"),
		("Enumerate", "nth", "Option"),
		("Enumerate", "nth_back", "Option"),
		("Enumerate", "peekable", "Peekable"),
		("Enumerate", "product", "u64"),
		("Enumerate", "reduce", "Option"),
		("Enumerate", "rev", "Rev"),
		("Enumerate", "size_hint", ""),
		("Enumerate", "skip", "Skip"),
		("Enumerate", "sum", "u64"),
		("Enumerate", "take", "Take"),
		("Filter", "all", "bool"),
		("Filter", "any", "bool"),
		("Filter", "chain", "Chain"),
		("Filter", "collect", "Vec"),
		("Filter", "count", "u64"),
		("Filter", "enumerate", "Enumerate"),
		("Filter", "filter", "Filter"),
		("Filter", "filter_map", "FilterMap"),
		("Filter", "find", "Option"),
		("Filter", "flat_map", "FlatMap"),
		("Filter", "fold", "any"),
		("Filter", "len", "u64"),
		("Filter", "map", "Map"),
		("Filter", "next", "Option"),
		("Filter", "next_back", "Option"),
		("Filter", "nth", "Option"),
		("Filter", "nth_back", "Option"),
		("Filter", "peekable", "Peekable"),
		("Filter", "product", "u64"),
		("Filter", "reduce", "Option"),
		("Filter", "rev", "Rev"),
		("Filter", "size_hint", ""),
		("Filter", "skip", "Skip"),
		("Filter", "sum", "u64"),
		("Filter", "take", "Take"),
		("FilterMap", "all", "bool"),
		("FilterMap", "any", "bool"),
		("FilterMap", "chain", "Chain"),
		("FilterMap", "collect", "Vec"),
		("FilterMap", "count", "u64"),
		("FilterMap", "enumerate", "Enumerate"),
		("FilterMap", "filter", "Filter"),
		("FilterMap", "filter_map", "FilterMap"),
		("FilterMap", "find", "Option"),
		("FilterMap", "flat_map", "FlatMap"),
		("FilterMap", "fold", "any"),
		("FilterMap", "len", "u64"),
		("FilterMap", "map", "Map"),
		("FilterMap", "next", "Option"),
		("FilterMap", "next_back", "Option"),
		("FilterMap", "nth", "Option"),
		("FilterMap", "nth_back", "Option"),
		("FilterMap", "peekable", "Peekable"),
		("FilterMap", "product", "u64"),
		("FilterMap", "reduce", "Option"),
		("FilterMap", "rev", "Rev"),
		("FilterMap", "size_hint", ""),
		("FilterMap", "skip", "Skip"),
		("FilterMap", "sum", "u64"),
		("FilterMap", "take", "Take"),
		("FlatMap", "all", "bool"),
		("FlatMap", "any", "bool"),
		("FlatMap", "chain", "Chain"),
		("FlatMap", "collect", "Vec"),
		("FlatMap", "count", "u64"),
		("FlatMap", "enumerate", "Enumerate"),
		("FlatMap", "filter", "Filter"),
		("FlatMap", "filter_map", "FilterMap"),
		("FlatMap", "find", "Option"),
		("FlatMap", "flat_map", "FlatMap"),
		("FlatMap", "fold", "any"),
		("FlatMap", "len", "u64"),
		("FlatMap", "map", "Map"),
		("FlatMap", "next", "Option"),
		("FlatMap", "next_back", "Option"),
		("FlatMap", "nth", "Option"),
		("FlatMap", "nth_back", "Option"),
		("FlatMap", "peekable", "Peekable"),
		("FlatMap", "product", "u64"),
		("FlatMap", "reduce", "Option"),
		("FlatMap", "rev", "Rev"),
		("FlatMap", "size_hint", ""),
		("FlatMap", "skip", "Skip"),
		("FlatMap", "sum", "u64"),
		("FlatMap", "take", "Take"),
		("Intersection", "all", "bool"),
		("Intersection", "any", "bool"),
		("Intersection", "chain", "Chain"),
		("Intersection", "collect", "Vec"),
		("Intersection", "count", "u64"),
		("Intersection", "enumerate", "Enumerate"),
		("Intersection", "filter", "Filter"),
		("Intersection", "filter_map", "FilterMap"),
		("Intersection", "find", "Option"),
		("Intersection", "flat_map", "FlatMap"),
		("Intersection", "fold", "any"),
		("Intersection", "len", "u64"),
		("Intersection", "map", "Map"),
		("Intersection", "next", "Option"),
		("Intersection", "next_back", "Option"),
		("Intersection", "nth", "Option"),
		("Intersection", "nth_back", "Option"),
		("Intersection", "peekable", "Peekable"),
		("Intersection", "product", "u64"),
		("Intersection", "reduce", "Option"),
		("Intersection", "rev", "Rev"),
		("Intersection", "size_hint", ""),
		("Intersection", "skip", "Skip"),
		("Intersection", "sum", "u64"),
		("Intersection", "take", "Take"),
		("Iter", "all", "bool"),
		("Iter", "any", "bool"),
		("Iter", "chain", "Chain"),
		("Iter", "collect", "Vec"),
		("Iter", "count", "u64"),
		("Iter", "enumerate", "Enumerate"),
		("Iter", "filter", "Filter"),
		("Iter", "filter_map", "FilterMap"),
		("Iter", "find", "Option"),
		("Iter", "flat_map", "FlatMap"),
		("Iter", "fold", "any"),
		("Iter", "len", "u64"),
		("Iter", "map", "Map"),
		("Iter", "next", "Option"),
		("Iter", "next_back", "Option"),
		("Iter", "nth", "Option"),
		("Iter", "nth_back", "Option"),
		("Iter", "peekable", "Peekable"),
		("Iter", "product", "u64"),
		("Iter", "reduce", "Option"),
		("Iter", "rev", "Rev"),
		("Iter", "size_hint", ""),
		("Iter", "skip", "Skip"),
		("Iter", "sum", "u64"),
		("Iter", "take", "Take"),
		("Keys", "all", "bool"),
		("Keys", "any", "bool"),
		("Keys", "chain", "Chain"),
		("Keys", "collect", "Vec"),
		("Keys", "count", "u64"),
		("Keys", "enumerate", "Enumerate"),
		("Keys", "filter", "Filter"),
		("Keys", "filter_map", "FilterMap"),
		("Keys", "find", "Option"),
		("Keys", "flat_map", "FlatMap"),
		("Keys", "fold", "any"),
		("Keys", "len", "u64"),
		("Keys", "map", "Map"),
		("Keys", "next", "Option"),
		("Keys", "next_back", "Option"),
		("Keys", "nth", "Option"),
		("Keys", "nth_back", "Option"),
		("Keys", "peekable", "Peekable"),
		("Keys", "product", "u64"),
		("Keys", "reduce", "Option"),
		("Keys", "rev", "Rev"),
		("Keys", "size_hint", ""),
		("Keys", "skip", "Skip"),
		("Keys", "sum", "u64"),
		("Keys", "take", "Take"),
		("Map", "all", "bool"),
		("Map", "any", "bool"),
		("Map", "chain", "Chain"),
		("Map", "collect", "Vec"),
		("Map", "count", "u64"),
		("Map", "enumerate", "Enumerate"),
		("Map", "filter", "Filter"),
		("Map", "filter_map", "FilterMap"),
		("Map", "find", "Option"),
		("Map", "flat_map", "FlatMap"),
		("Map", "fold", "any"),
		("Map", "len", "u64"),
		("Map", "map", "Map"),
		("Map", "next", "Option"),
		("Map", "next_back", "Option"),
		("Map", "nth", "Option"),
		("Map", "nth_back", "Option"),
		("Map", "peekable", "Peekable"),
		("Map", "product", "u64"),
		("Map", "reduce", "Option"),
		("Map", "rev", "Rev"),
		("Map", "size_hint", ""),
		("Map", "skip", "Skip"),
		("Map", "sum", "u64"),
		("Map", "take", "Take"),
		("Once", "all", "bool"),
		("Once", "any", "bool"),
		("Once", "chain", "Chain"),
		("Once", "collect", "Vec"),
		("Once", "count", "u64"),
		("Once", "enumerate", "Enumerate"),
		("Once", "filter", "Filter"),
		("Once", "filter_map", "FilterMap"),
		("Once", "find", "Option"),
		("Once", "flat_map", "FlatMap"),
		("Once", "fold", "any"),
		("Once", "len", "u64"),
		("Once", "map", "Map"),
		("Once", "next", "Option"),
		("Once", "next_back", "Option"),
		("Once", "nth", "Option"),
		("Once", "nth_back", "Option"),
		("Once", "peekable", "Peekable"),
		("Once", "product", "u64"),
		("Once", "reduce", "Option"),
		("Once", "rev", "Rev"),
		("Once", "size_hint", ""),
		("Once", "skip", "Skip"),
		("Once", "sum", "u64"),
		("Once", "take", "Take"),
		("Peekable", "all", "bool"),
		("Peekable", "any", "bool"),
		("Peekable", "chain", "Chain"),
		("Peekable", "collect", "Vec"),
		("Peekable", "count", "u64"),
		("Peekable", "enumerate", "Enumerate"),
		("Peekable", "filter", "Filter"),
		("Peekable", "filter_map", "FilterMap"),
		("Peekable", "find", "Option"),
		("Peekable", "flat_map", "FlatMap"),
		("Peekable", "fold", "any"),
		("Peekable", "len", "u64"),
		("Peekable", "map", "Map"),
		("Peekable", "next", "Option"),
		("Peekable", "next_back", "Option"),
		("Peekable", "nth", "Option"),
		("Peekable", "nth_back", "Option"),
		("Peekable", "peek", "Option"),
		("Peekable", "peekable", "Peekable"),
		("Peekable", "product", "u64"),
		("Peekable", "reduce", "Option"),
		("Peekable", "rev", "Rev"),
		("Peekable", "size_hint", ""),
		("Peekable", "skip", "Skip"),
		("Peekable", "sum", "u64"),
		("Peekable", "take", "Take"),
		("Range", "all", "bool"),
		("Range", "any", "bool"),
		("Range", "chain", "Chain"),
		("Range", "collect", "Vec"),
		("Range", "count", "u64"),
		("Range", "enumerate", "Enumerate"),
		("Range", "filter", "Filter"),
		("Range", "filter_map", "FilterMap"),
		("Range", "find", "Option"),
		("Range", "flat_map", "FlatMap"),
		("Range", "fold", "any"),
		("Range", "len", "u64"),
		("Range", "map", "Map"),
		("Range", "next", "Option"),
		("Range", "next_back", "Option"),
		("Range", "nth", "Option"),
		("Range", "nth_back", "Option"),
		("Range", "peekable", "Peekable"),
		("Range", "product", "u64"),
		("Range", "reduce", "Option"),
		("Range", "rev", "Rev"),
		("Range", "size_hint", ""),
		("Range", "skip", "Skip"),
		("Range", "sum", "u64"),
		("Range", "take", "Take"),
		("RangeFrom", "all", "bool"),
		("RangeFrom", "any", "bool"),
		("RangeFrom", "chain", "Chain"),
		("RangeFrom", "collect", "Vec"),
		("RangeFrom", "count", "u64"),
		("RangeFrom", "enumerate", "Enumerate"),
		("RangeFrom", "filter", "Filter"),
		("RangeFrom", "filter_map", "FilterMap"),
		("RangeFrom", "find", "Option"),
		("RangeFrom", "flat_map", "FlatMap"),
		("RangeFrom", "fold", "any"),
		("RangeFrom", "len", "u64"),
		("RangeFrom", "map", "Map"),
		("RangeFrom", "next", "Option"),
		("RangeFrom", "next_back", "Option"),
		("RangeFrom", "nth", "Option"),
		("RangeFrom", "nth_back", "Option"),
		("RangeFrom", "peekable", "Peekable"),
		("RangeFrom", "product", "u64"),
		("RangeFrom", "reduce", "Option"),
		("RangeFrom", "rev", "Rev"),
		("RangeFrom", "size_hint", ""),
		("RangeFrom", "skip", "Skip"),
		("RangeFrom", "sum", "u64"),
		("RangeFrom", "take", "Take"),
		("RangeFromIter", "all", "bool"),
		("RangeFromIter", "any", "bool"),
		("RangeFromIter", "chain", "Chain"),
		("RangeFromIter", "collect", "Vec"),
		("RangeFromIter", "count", "u64"),
		("RangeFromIter", "enumerate", "Enumerate"),
		("RangeFromIter", "filter", "Filter"),
		("RangeFromIter", "filter_map", "FilterMap"),
		("RangeFromIter", "find", "Option"),
		("RangeFromIter", "flat_map", "FlatMap"),
		("RangeFromIter", "fold", "any"),
		("RangeFromIter", "len", "u64"),
		("RangeFromIter", "map", "Map"),
		("RangeFromIter", "next", "Option"),
		("RangeFromIter", "next_back", "Option"),
		("RangeFromIter", "nth", "Option"),
		("RangeFromIter", "nth_back", "Option"),
		("RangeFromIter", "peekable", "Peekable"),
		("RangeFromIter", "product", "u64"),
		("RangeFromIter", "reduce", "Option"),
		("RangeFromIter", "rev", "Rev"),
		("RangeFromIter", "size_hint", ""),
		("RangeFromIter", "skip", "Skip"),
		("RangeFromIter", "sum", "u64"),
		("RangeFromIter", "take", "Take"),
		("RangeInclusive", "all", "bool"),
		("RangeInclusive", "any", "bool"),
		("RangeInclusive", "chain", "Chain"),
		("RangeInclusive", "collect", "Vec"),
		("RangeInclusive", "count", "u64"),
		("RangeInclusive", "enumerate", "Enumerate"),
		("RangeInclusive", "filter", "Filter"),
		("RangeInclusive", "filter_map", "FilterMap"),
		("RangeInclusive", "find", "Option"),
		("RangeInclusive", "flat_map", "FlatMap"),
		("RangeInclusive", "fold", "any"),
		("RangeInclusive", "len", "u64"),
		("RangeInclusive", "map", "Map"),
		("RangeInclusive", "next", "Option"),
		("RangeInclusive", "next_back", "Option"),
		("RangeInclusive", "nth", "Option"),
		("RangeInclusive", "nth_back", "Option"),
		("RangeInclusive", "peekable", "Peekable"),
		("RangeInclusive", "product", "u64"),
		("RangeInclusive", "reduce", "Option"),
		("RangeInclusive", "rev", "Rev"),
		("RangeInclusive", "size_hint", ""),
		("RangeInclusive", "skip", "Skip"),
		("RangeInclusive", "sum", "u64"),
		("RangeInclusive", "take", "Take"),
		("RangeInclusiveIter", "all", "bool"),
		("RangeInclusiveIter", "any", "bool"),
		("RangeInclusiveIter", "chain", "Chain"),
		("RangeInclusiveIter", "collect", "Vec"),
		("RangeInclusiveIter", "count", "u64"),
		("RangeInclusiveIter", "enumerate", "Enumerate"),
		("RangeInclusiveIter", "filter", "Filter"),
		("RangeInclusiveIter", "filter_map", "FilterMap"),
		("RangeInclusiveIter", "find", "Option"),
		("RangeInclusiveIter", "flat_map", "FlatMap"),
		("RangeInclusiveIter", "fold", "any"),
		("RangeInclusiveIter", "len", "u64"),
		("RangeInclusiveIter", "map", "Map"),
		("RangeInclusiveIter", "next", "Option"),
		("RangeInclusiveIter", "next_back", "Option"),
		("RangeInclusiveIter", "nth", "Option"),
		("RangeInclusiveIter", "nth_back", "Option"),
		("RangeInclusiveIter", "peekable", "Peekable"),
		("RangeInclusiveIter", "product", "u64"),
		("RangeInclusiveIter", "reduce", "Option"),
		("RangeInclusiveIter", "rev", "Rev"),
		("RangeInclusiveIter", "size_hint", ""),
		("RangeInclusiveIter", "skip", "Skip"),
		("RangeInclusiveIter", "sum", "u64"),
		("RangeInclusiveIter", "take", "Take"),
		("RangeIter", "all", "bool"),
		("RangeIter", "any", "bool"),
		("RangeIter", "chain", "Chain"),
		("RangeIter", "collect", "Vec"),
		("RangeIter", "count", "u64"),
		("RangeIter", "enumerate", "Enumerate"),
		("RangeIter", "filter", "Filter"),
		("RangeIter", "filter_map", "FilterMap"),
		("RangeIter", "find", "Option"),
		("RangeIter", "flat_map", "FlatMap"),
		("RangeIter", "fold", "any"),
		("RangeIter", "len", "u64"),
		("RangeIter", "map", "Map"),
		("RangeIter", "next", "Option"),
		("RangeIter", "next_back", "Option"),
		("RangeIter", "nth", "Option"),
		("RangeIter", "nth_back", "Option"),
		("RangeIter", "peekable", "Peekable"),
		("RangeIter", "product", "u64"),
		("RangeIter", "reduce", "Option"),
		("RangeIter", "rev", "Rev"),
		("RangeIter", "size_hint", ""),
		("RangeIter", "skip", "Skip"),
		("RangeIter", "sum", "u64"),
		("RangeIter", "take", "Take"),
		("Rev", "all", "bool"),
		("Rev", "any", "bool"),
		("Rev", "chain", "Chain"),
		("Rev", "collect", "Vec"),
		("Rev", "count", "u64"),
		("Rev", "enumerate", "Enumerate"),
		("Rev", "filter", "Filter"),
		("Rev", "filter_map", "FilterMap"),
		("Rev", "find", "Option"),
		("Rev", "flat_map", "FlatMap"),
		("Rev", "fold", "any"),
		("Rev", "len", "u64"),
		("Rev", "map", "Map"),
		("Rev", "next", "Option"),
		("Rev", "next_back", "Option"),
		("Rev", "nth", "Option"),
		("Rev", "nth_back", "Option"),
		("Rev", "peekable", "Peekable"),
		("Rev", "product", "u64"),
		("Rev", "reduce", "Option"),
		("Rev", "rev", "Rev"),
		("Rev", "size_hint", ""),
		("Rev", "skip", "Skip"),
		("Rev", "sum", "u64"),
		("Rev", "take", "Take"),
		("Skip", "all", "bool"),
		("Skip", "any", "bool"),
		("Skip", "chain", "Chain"),
		("Skip", "collect", "Vec"),
		("Skip", "count", "u64"),
		("Skip", "enumerate", "Enumerate"),
		("Skip", "filter", "Filter"),
		("Skip", "filter_map", "FilterMap"),
		("Skip", "find", "Option"),
		("Skip", "flat_map", "FlatMap"),
		("Skip", "fold", "any"),
		("Skip", "len", "u64"),
		("Skip", "map", "Map"),
		("Skip", "next", "Option"),
		("Skip", "next_back", "Option"),
		("Skip", "nth", "Option"),
		("Skip", "nth_back", "Option"),
		("Skip", "peekable", "Peekable"),
		("Skip", "product", "u64"),
		("Skip", "reduce", "Option"),
		("Skip", "rev", "Rev"),
		("Skip", "size_hint", ""),
		("Skip", "skip", "Skip"),
		("Skip", "sum", "u64"),
		("Skip", "take", "Take"),
		("Split", "all", "bool"),
		("Split", "any", "bool"),
		("Split", "chain", "Chain"),
		("Split", "collect", "Vec"),
		("Split", "count", "u64"),
		("Split", "enumerate", "Enumerate"),
		("Split", "filter", "Filter"),
		("Split", "filter_map", "FilterMap"),
		("Split", "find", "Option"),
		("Split", "flat_map", "FlatMap"),
		("Split", "fold", "any"),
		("Split", "len", "u64"),
		("Split", "map", "Map"),
		("Split", "next", "Option"),
		("Split", "next_back", "Option"),
		("Split", "nth", "Option"),
		("Split", "nth_back", "Option"),
		("Split", "peekable", "Peekable"),
		("Split", "product", "u64"),
		("Split", "reduce", "Option"),
		("Split", "rev", "Rev"),
		("Split", "size_hint", ""),
		("Split", "skip", "Skip"),
		("Split", "sum", "u64"),
		("Split", "take", "Take"),
		("Take", "all", "bool"),
		("Take", "any", "bool"),
		("Take", "chain", "Chain"),
		("Take", "collect", "Vec"),
		("Take", "count", "u64"),
		("Take", "enumerate", "Enumerate"),
		("Take", "filter", "Filter"),
		("Take", "filter_map", "FilterMap"),
		("Take", "find", "Option"),
		("Take", "flat_map", "FlatMap"),
		("Take", "fold", "any"),
		("Take", "len", "u64"),
		("Take", "map", "Map"),
		("Take", "next", "Option"),
		("Take", "next_back", "Option"),
		("Take", "nth", "Option"),
		("Take", "nth_back", "Option"),
		("Take", "peekable", "Peekable"),
		("Take", "product", "u64"),
		("Take", "reduce", "Option"),
		("Take", "rev", "Rev"),
		("Take", "size_hint", ""),
		("Take", "skip", "Skip"),
		("Take", "sum", "u64"),
		("Take", "take", "Take"),
		("Union", "all", "bool"),
		("Union", "any", "bool"),
		("Union", "chain", "Chain"),
		("Union", "collect", "Vec"),
		("Union", "count", "u64"),
		("Union", "enumerate", "Enumerate"),
		("Union", "filter", "Filter"),
		("Union", "filter_map", "FilterMap"),
		("Union", "find", "Option"),
		("Union", "flat_map", "FlatMap"),
		("Union", "fold", "any"),
		("Union", "len", "u64"),
		("Union", "map", "Map"),
		("Union", "next", "Option"),
		("Union", "next_back", "Option"),
		("Union", "nth", "Option"),
		("Union", "nth_back", "Option"),
		("Union", "peekable", "Peekable"),
		("Union", "product", "u64"),
		("Union", "reduce", "Option"),
		("Union", "rev", "Rev"),
		("Union", "size_hint", ""),
		("Union", "skip", "Skip"),
		("Union", "sum", "u64"),
		("Union", "take", "Take"),
		("Values", "all", "bool"),
		("Values", "any", "bool"),
		("Values", "chain", "Chain"),
		("Values", "collect", "Vec"),
		("Values", "count", "u64"),
		("Values", "enumerate", "Enumerate"),
		("Values", "filter", "Filter"),
		("Values", "filter_map", "FilterMap"),
		("Values", "find", "Option"),
		("Values", "flat_map", "FlatMap"),
		("Values", "fold", "any"),
		("Values", "len", "u64"),
		("Values", "map", "Map"),
		("Values", "next", "Option"),
		("Values", "next_back", "Option"),
		("Values", "nth", "Option"),
		("Values", "nth_back", "Option"),
		("Values", "peekable", "Peekable"),
		("Values", "product", "u64"),
		("Values", "reduce", "Option"),
		("Values", "rev", "Rev"),
		("Values", "size_hint", ""),
		("Values", "skip", "Skip"),
		("Values", "sum", "u64"),
		("Values", "take", "Take"),
	])
}

/// `rune::modules::ops`
pub fn ops() -> Vec<MethodSignature> {
	table(&[
		("Range", "contains", "bool"),
		("Range", "iter", "any"),
		("RangeFrom", "contains", "bool"),
		("RangeFrom", "iter", "any"),
		("RangeFull", "contains", "bool"),
		("RangeInclusive", "contains", "bool"),
		("RangeInclusive", "iter", "any"),
		("RangeTo", "contains", "bool"),
		("RangeToInclusive", "contains", "bool"),
	])
}

/// `rune::modules::generator`
pub fn generator() -> Vec<MethodSignature> {
	table(&[
		("Generator", "iter", "Iter"),
		("Generator", "next", "Option"),
		("Generator", "resume", "GeneratorState"),
	])
}

/// `rune::modules::mem`
pub fn mem() -> Vec<MethodSignature> {
	table(&[
		("Snapshot", "is_exclusive", "bool"),
		("Snapshot", "is_readable", "bool"),
		("Snapshot", "is_writable", "bool"),
		("Snapshot", "shared", "u64"),
	])
}

/// `rune::modules::test`
pub fn test() -> Vec<MethodSignature> {
	table(&[
		("Bencher", "iter", ""),
	])
}

/// `rune::modules::stream`
pub fn stream() -> Vec<MethodSignature> {
	table(&[
		("Stream", "next", "Option"),
		("Stream", "resume", "GeneratorState"),
	])
}

/// The whole standard library — for hosts using
/// `Context::with_default_modules()`.
pub fn rune_std_methods() -> Vec<MethodSignature> {
	let mut out = Vec::new();
	out.extend(string());
	out.extend(bytes());
	out.extend(vec());
	out.extend(object());
	out.extend(tuple());
	out.extend(hash_map());
	out.extend(hash_set());
	out.extend(vec_deque());
	out.extend(char());
	out.extend(i64());
	out.extend(u64());
	out.extend(f64());
	out.extend(option());
	out.extend(result());
	out.extend(iter());
	out.extend(ops());
	out.extend(generator());
	out.extend(mem());
	out.extend(test());
	out.extend(stream());
	out
}
